import Head from 'next/head';
import { useRouter } from 'next/router';
import { ReactElement } from 'react';

import Footer from '@/components/footer';
import Header from '@/components/header';
import CardList from '@/components/card-list';
import { Character, Info } from '@/interfaces/api-types';

type Props = {
  data: Info<Character[]>;
  children?: ReactElement;
};

export default function Layout({ children, data }: Props) {
  const router = useRouter();
  const isPatchCharacter = router.pathname.includes('/character/');

  return (
    <>
      <Head>
        <title>The Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <main className={`container ${isPatchCharacter ? 'opened' : ''}`}>
        <div>
          <CardList data={data} />
        </div>
        <div>{children}</div>
      </main>
      <Footer />
    </>
  );
}
